"""Exercise duplicate webhook delivery protection against real PostgreSQL."""
import asyncio
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import Mock
from uuid import uuid4

import pgserver
import psycopg
import pytest

from src.utils.generation_storage import GenerationStorage

MIGRATION = (Path(__file__).resolve().parents[2] /
             'supabase/migrations/20261009220000_deduplicate_paid_orders.sql').read_text()


@pytest.fixture(scope='module')
def server(tmp_path_factory):
    instance = pgserver.get_server(tmp_path_factory.mktemp('paid-order-deduplication'), cleanup_mode='delete')
    yield instance
    instance.cleanup()


@pytest.fixture
def db(server):
    with psycopg.connect(server.get_uri(), autocommit=True) as connection:
        connection.execute('DROP TABLE IF EXISTS public.orders CASCADE')
        connection.execute('DROP FUNCTION IF EXISTS public.prevent_duplicate_paid_order()')
        for role in ['anon', 'authenticated', 'service_role']:
            if not connection.execute('SELECT 1 FROM pg_roles WHERE rolname = %s', (role,)).fetchone():
                connection.execute(f'CREATE ROLE {role}')
        connection.execute('''CREATE TABLE public.orders (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            generation_id uuid, amount_paid text, stripe_session_id text,
            stripe_payment_intent text, shipping_info jsonb,
            created_at timestamptz NOT NULL DEFAULT now(), fulfilled boolean DEFAULT false
        )''')
        yield connection


def insert(db, generation, session='cs_order', payment='pi_order', amount='20.17'):
    return db.execute('''INSERT INTO public.orders
        (generation_id, amount_paid, stripe_session_id, stripe_payment_intent)
        VALUES (%s, %s, %s, %s) RETURNING id''', (generation, amount, session, payment)).fetchone()


def test_repeat_session_and_repeat_payment_do_not_create_an_order(db):
    db.execute(MIGRATION)
    generation = uuid4()
    first = insert(db, generation)
    assert insert(db, generation) is None
    assert insert(db, generation, session='cs_other') is None
    assert insert(db, generation, payment=None) is None
    assert db.execute('SELECT id FROM public.orders').fetchall() == [first]
    # Buying the same model again with a new payment is still valid.
    assert insert(db, generation, session='cs_new', payment='pi_new') is not None


def test_concurrent_deliveries_create_exactly_one_order(db, server):
    db.execute(MIGRATION)
    generation = uuid4()

    def deliver(_):
        with psycopg.connect(server.get_uri(), autocommit=True) as connection:
            return insert(connection, generation)

    with ThreadPoolExecutor(max_workers=8) as pool:
        results = list(pool.map(deliver, range(16)))
    assert sum(result is not None for result in results) == 1
    assert db.execute('SELECT count(*) FROM public.orders').fetchone() == (1,)


def test_concurrent_sessions_for_the_same_payment_create_one_order(db, server):
    db.execute(MIGRATION)
    generation = uuid4()

    def deliver(i):
        with psycopg.connect(server.get_uri(), autocommit=True) as connection:
            return insert(connection, generation, session=f'cs_{i}')

    with ThreadPoolExecutor(max_workers=4) as pool:
        results = list(pool.map(deliver, range(8)))
    assert sum(result is not None for result in results) == 1
    assert db.execute('SELECT count(*) FROM public.orders').fetchone() == (1,)


def test_migration_preserves_historical_duplicates_but_blocks_more(db):
    generation = uuid4()
    original = insert(db, generation)
    duplicate = insert(db, generation)
    db.execute(MIGRATION)
    assert insert(db, generation) is None
    assert db.execute('SELECT id FROM public.orders ORDER BY id').fetchall() == [original, duplicate]


@pytest.mark.parametrize('change', ['generation', 'amount', 'payment'])
def test_conflicting_details_are_rejected_instead_of_silently_accepted(db, change):
    db.execute(MIGRATION)
    generation = uuid4()
    first = insert(db, generation)
    with pytest.raises(psycopg.errors.RaiseException, match='conflict with an existing order'):
        insert(db, uuid4() if change == 'generation' else generation,
               amount='21.17' if change == 'amount' else '20.17',
               payment='pi_different' if change == 'payment' else 'pi_order')
    assert db.execute('SELECT id FROM public.orders').fetchall() == [first]


def test_rolled_back_insert_does_not_block_the_next_delivery(db):
    db.execute(MIGRATION)
    generation = uuid4()
    with pytest.raises(RuntimeError):
        with db.transaction():
            assert insert(db, generation) is not None
            raise RuntimeError('Simulated failure before commit')
    assert db.execute('SELECT count(*) FROM public.orders').fetchone() == (0,)
    assert insert(db, generation) is not None


def test_manual_orders_and_function_permissions_are_preserved(db):
    db.execute(MIGRATION)
    generation = uuid4()
    assert insert(db, generation, session=None, payment=None) is not None
    assert insert(db, generation, session=None, payment=None) is not None
    for role in ['anon', 'authenticated']:
        assert db.execute("SELECT has_function_privilege(%s, 'public.prevent_duplicate_paid_order()', 'EXECUTE')",
                          (role,)).fetchone() == (False,)


def test_storage_skips_generation_update_when_database_suppresses_the_insert():
    orders = Mock()
    orders.insert.return_value.execute.return_value = SimpleNamespace(data=[])
    client = Mock()
    client.table.return_value = orders
    storage = GenerationStorage.__new__(GenerationStorage)
    storage.client = client
    assert asyncio.run(storage.update_payment_status('g', 2017, 'cs_order', 'pi_order')) is None
    client.table.assert_called_once_with('orders')
    orders.update.assert_not_called()
